service: flashlex-web

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    $ref: ./devIamRoleStatements.json
custom:
  pythonRequirements:
    dockerizePip: true

package:
 include:
   - config/**

functions:
  auth:
    handler: auth.authorize
  getInfo:
    handler: handler.getInfo
    events:
      - http:
          path: /info
          method: get
          integration: lambda-proxy
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
